version: "2017-09-20"
dependencies:
  - id: base_ubuntu
    type: docker
    ref: registry.opensource.zalan.do/stups/ubuntu
pipeline:
  - id: build
    type: script
    env:
      IMAGE: registry-write.opensource.zalan.do/stups/python
    commands:
    - desc: Build the docker image
      cmd: |
        # Use the resolved Ubuntu base image version
        echo "Ubuntu base image version: ${DEP_BASE_UBUNTU_VERSION}"
        docker build --squash \
                     --tag ${IMAGE}:local \
                     --build-arg UBUNTU_VERSION=${DEP_BASE_UBUNTU_VERSION} \
                     .

        # Get current Python version
        PYTHON_VERSION=$(docker run ${IMAGE}:local python -V | awk '{ print $2}')
        echo "Successfully built docker image with Python version: ${PYTHON_VERSION}"

        # Tag and push the image (but only if it is a master branch)
        if [ -z "$CDP_PULL_REQUEST_NUMBER" ]; then
          TAG=${PYTHON_VERSION}-${CDP_TARGET_BRANCH_COUNTER}
          docker tag ${IMAGE}:local ${IMAGE}:${TAG}
          docker push ${IMAGE}:${TAG}
        else
          echo "Image not pushed because the build is not a push to master"
        fi
